### ISSUE TITLE
Cannot convert data to Rhai dynamic error

### ISSUE THREAD

**Issue by technosophos** [fermyon/bartholomew#10]
When a runtime error occurs with Rhai, we almost always get the same largely uninformative error:

For example, say we have this `content/borken.md`:

```toml
title = "Example of broken page"
template = "borken" # <-- uses borken.hbs
date = "2021-12-23T17:05:19Z"
---
```

And this `templates/borken.hbs`:

```handlebars
{{ borken }} <-- invokes the `borken.rhai`
```

And this `scripts/borken.rhai`:

```rust
// Note that msg is undefined, but this will parse.
// So it will generate a runtime error instead of a parse error.
"hello " + msg;
```

The result of executing the above would yield:

```
Rendering "/content/borken.md": Template 'borken': Error rendering "borken" line 1, col 1: Cannot convert data to Rhai dynamic
```

I can't figure out how to get a better error message out of the Handlebars engine.

Note that a parse error is much easier to debug, and it would be nice to have something closer to this:

```
Script "/scripts/borken.rhai": ParseError(ParseError(MissingToken(")", "to close the arguments list of this function call 'f'"), 5:3))
```
